#!/bin/bash

## #ddev-generated
## Description: This script is part of "tyler36/ddev-tinker". It's purpose is to download
##              Psysh's PHP core documentation. After starting a "ddev tinker" session,
##              type "doc date", where 'date' is any core PHP function. It will display a
##              man-like page detailing the function.
##              @see https://github.com/bobthecow/psysh/wiki/PHP-manual
##              This addon does a "simple" (and naive) language check to see if the developer
##              may prefer a different locale. See "Example" below to "fake" a non-English setup.
## Usage: get-php-manual
## Example: "ddev get-php-manual"
## Example: "LANG=ja_JP.UTF8 ddev get-php-manual"

mkdir -p "$DDEV_APPROOT/.ddev/homeadditions/.local/share/psysh"

FILENAME=php_manual.sqlite
BASE_URL="http://psysh.org/manual"

echo "Detected host language: ${LANG}"

## Parse the LANG and see if the developer has a non-English language
case "${LANG}" in
    de* )
        ## Assume German from "LANG=de_DE.UTF-8"
        MANUAL="de/$FILENAME"
        MAN_LOCALE="Deutsches Handbuch"
        ;;
    fr* )
        ## Assume French from "LANG=fr_FR.UTF-8"
        MANUAL="fr/$FILENAME"
        MAN_LOCALE="Manuel en français"
        ;;
    ja* )
        ## Assume Japanese from "LANG=ja_JP.UTF8"
        MANUAL="ja/$FILENAME"
        MAN_LOCALE="日本語マニュアル"
        ;;
    ru* )
        ## Assume Russian from "LANG=ru_RU.UTF-8"
        MANUAL="ru/$FILENAME"
        MAN_LOCALE="Manuel russe"
        ;;
    * )
        ## Default to English
        MANUAL="en/$FILENAME"
        MAN_LOCALE="English manual"
        ;;
esac

echo "Downloading: ${MAN_LOCALE}"
curl -sSL "$BASE_URL/$MANUAL" -o "$DDEV_APPROOT/.ddev/homeadditions/.local/share/psysh/$FILENAME"
echo "Restart the project to copy the manual into the container."
